# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b92bc6ea880ea99b53d54fe3b661507b01ba5dac2ac591fe3c5e1e0ea0b09d2e9b166b978bacf65ebddd731942e982e5a9f5e2f1ec9f745472aaf0dbe0477bbb
  stats_secret: stats_secret

test:
  secret_key_base: d5b139a995c3822485077c49a73d8ca66b84ce81d5694169b8eacad788fdddddcce352914ab2cdfaf11025c8a05499cda8b86eaf446ba98e43b8e83bd1920007
  stats_secret: stats_secret

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stats_secret: <%= ENV["STATS_SECRET"] %>
